### ISSUE TITLE
WiiLink Patcher closes when typing 1 at the beginning

### ISSUE THREAD

**Issue by AndytheGamer329** [WiiLink24/WiiLink24-Patcher#50]
I tried to use the latest release of WiiLink Patcher, but as soon as I type 1 and press enter on the main screen to do something, it closes. No matter what I do it doesn't seem to be fixed. Some desperate help would be very appreciated.

**Comment by PablosCorner** [comment]
You don't have to press Enter anymore (as of v.1.0.8), you can press the number and it will work.

**Comment by AndytheGamer329** [comment]
Umm... No it doesn't. It just closes as soon as I press 1.

**Comment by PablosCorner** [comment]
I see, may I ask what OS you're using?

**Comment by AndytheGamer329** [comment]
I'm using Windows 11.

...Please don't tell me this thing doesn't work on Windows 11... does it...?

**Comment by PablosCorner** [comment]
That's bizarre, I developed and tested the script on Windows 11. Could you open Windows Terminal or CMD and start the script from there, and tell me if anything strange pops up?

**Comment by AndytheGamer329** [comment]
Okay.

I tried opening it in CMD and it says, "05 was unexpected at this time."

**Comment by PablosCorner** [comment]
Interesting. I can't seem to replicate the issue on my end on Windows 11, nor can I find any "05" in the batch script code. Try downloading the .bat script again and see if it still gives you the issue. If not, I'd say record a video of you trying to use the script and I can try to go from there.

**Comment by AndytheGamer329** [comment]
Okay. I re-downloaded it and I tried to open it with Powershell. This it the result that I recoreded.
https://user-images.githubusercontent.com/90027310/221977837-8f97d60b-da29-4569-979a-13c432bb7292.mp4

**Comment by PablosCorner** [comment]
Oh interesting, I see Korean text in the CMD, what is your locale set to?

**Comment by AndytheGamer329** [comment]
Um... To South Korea as for now.

Was I supposed to set the locale setting to the specific one that I want to use this...?

**Comment by AndytheGamer329** [comment]
Can't believe that was the issue >:(

No problem! Thank you for helping me out as well. Really appreiciate it :)

Oh and one more thing. I'm trying to install the WiiLink patched wads to my Wii that's converted to japanese. Will it work?

**Comment by PablosCorner** [comment]
I'll try out some fixes and see if I can get it to work with all locales, if so, I'll report back.

**Comment by PablosCorner** [comment]
Okay, after some quick tweaking, I think I got it working on the Korean (and even Japanese) locale, I'll do some more internal testing, and then release an update!

**Comment by AndytheGamer329** [comment]
Sounds great 👍
Can't wait for the release 🙏

**Comment by PablosCorner** [comment]
I pushed a nightly build, if you check out the nightly branch, see if that fixes your issue.

**Comment by AndytheGamer329** [comment]
Okay👌
I'll check if it works properly now.

**Comment by AndytheGamer329** [comment]
Hmm.... Unfortunately it's still not working... :(
Now this happens:
<img width="867" alt="화면 캡처 2023-03-05 091540" src="https://user-images.githubusercontent.com/90027310/222934920-873c1e70-8e81-4259-b0fd-b79fa2016971.png">

**Comment by PablosCorner** [comment]
Ahhh Batch is really picky isn't it. I'll look into it more.

**Comment by AndytheGamer329** [comment]
Gotcha 👌

P.S. I actually forgot to tell you that I've tried to switch my local settings to USA and that with way it works. But I'm neither living in the States nor Japan so probably the digicam and demae channel's actual features are not gonna work lol

**Comment by PablosCorner** [comment]
Digicam should work regardless cause you just get emailed the photos you want. For Demae, you could still use the standard version which has fake ordering.

**Comment by AndytheGamer329** [comment]
Oh.
That makes sense. I was actually kinda worried if something dumb happens since I've actually wrote my package forwarding center's address in Japan lol
So you can only order actuall food in Demae channel if you're living in the States as for now right?

**Comment by PablosCorner** [comment]
Right now, Demae Dominos is only available in the US and Cananda. If you use the standard version, you can use it anywhere cause everything's simulated.

**Comment by AndytheGamer329** [comment]
Ok understood 👌
It's still mind blowing that you can actually order something with a console that's like 17 years old lol I'm actually curious how'd you guys all set it up
I hope we can get more places to work with this 🙏 Even though I don't live in the States XD

**Comment by PablosCorner** [comment]
I pushed another build to clear up the formatting for some of the commands, so if you want to try it again and see if it works on your end or not, I'd appreciate the feedback!

**Comment by AndytheGamer329** [comment]
Hi. Sorry for the late reply 😞
I tried it out and... It still wasn't working... :( Now when I press 1 it just repeats the main menu over and over.
<img width="867" alt="스크린샷_20230307_124913" src="https://user-images.githubusercontent.com/90027310/223161774-73406e3c-4902-41e5-a73a-250ffc5ccf75.png">

**Comment by PablosCorner** [comment]
Interesting, I'll restore some of the changes I had done, but since I know it wasn't fully working before, I'll still need to figure out a solution to make it work for your setup.

**Comment by PablosCorner** [comment]
I pushed out another nightly build, if it bugs out, please let me know!

**Comment by PablosCorner** [comment]
If you're interested in trying a new (potential) replacement for the Batch script, check this branch out.
[https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver](https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver)

**Comment by AndytheGamer329** [comment]
Okay I tried both of them and the C-Sharp version was working fine(Even though I had some issues building the project with Visual Studio XD). But the nightly build was still having issues :( I can see why people becomes batch file haters lol
This is what happened this time:
<img width="867" alt="스크린샷_20230307_015403" src="https://user-images.githubusercontent.com/90027310/223358910-7cbb148e-6dce-4d31-9103-7eb6d05f6942.png">

**Comment by PablosCorner** [comment]
I'm glad to hear the C# version working for you at least, though there was a download link in the README for it, haha. And yeah, I learned the hard way about Batch, lmao.

**Comment by PablosCorner** [comment]
Gonna close this as you mentioned the C# version worked fine for you.
